use_field_init_shorthand = true
# width_heuristics = "Max"
use_try_shorthand = true
newline_style = "Unix"

# - nightly features
# wrap_comments = true
# format_code_in_doc_comments = true
# normalize_comments = true
# reorder_impl_items = true
# overflow_delimited_expr = true
# match_block_trailing_comma = true
# condense_wildcard_suffixes = true
# format_strings = true
