name: Rust CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose

    - uses: actions/upload-artifact@v2
      with:
        name: copyrat-macos.zip
        path: ./target/release/*copyrat


  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run:  |
        sudo apt update -y
        sudo apt-get install -y curl gnupg ca-certificates git gcc-multilib g++-multilib cmake libssl-dev pkg-config python

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose

    - uses: actions/upload-artifact@v2
      with:
        name: copyrat-linux.zip
        path: ./target/release/*copyrat
